name: Python application

on:
  push:  
    branches: [ master, dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: |
        git fetch --prune --unshallow
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pip install pytest
        export PYTHONPATH=src
        pytest
    - name: Inspect envs
      run: |
        echo "GITHUB_REF=$GITHUB_REF"
        echo "GITHUB_REF_NAME=$GITHUB_REF_NAME"
        if [[ $GITHUB_REF_NAME = "master" ]]; then
            echo "ENV_NAME=production"
        else
            echo "ENV_NAME=development"
        fi
        if [[ $GITHUB_REF_NAME = "dev" ]]; then
            echo "branch is dev"
        else
            echo "branch is master"
        fi
        
