name: Python application

on:
  workflow_dispatch:
    inputs: {}
  push:
    tags:
      - '*'
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: |
        git fetch --prune --unshallow
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pip install pytest
        export PYTHONPATH=src
        pytest
    - uses: earthly/actions-setup@v1
      with:
        version: v0.8.15
    - name: test it with earthly
      run: |
        earthly --allow-privileged +integration-test-api    
    - name: Build ci version image and api test from outside host
      run: |
        earthly --allow-privileged +integration-test-api
    - name: Inspect envs
      run: |
        echo "GITHUB_REF=$GITHUB_REF"
        echo "GITHUB_REF_NAME=$GITHUB_REF_NAME"
        echo "GITHUB_SHA=$GITHUB_SHA"
        env
        git describe --tags --long
        if [[ "$GITHUB_REF_NAME" = *"dev" ]]; then
            echo "ENV_NAME=development"
        else
            echo "ENV_NAME=production"
        fi
        if [[ "$GITHUB_REF_NAME" = *"dev" ]]; then
            echo "this is more like a dev release"
        else
            echo "this is more like a main release"
        fi
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        provenance: false
        push: true
        tags: |
          ghcr.io/${{ github.repository }}:${{ github.ref_name }}
          ${{ endsWith(github.ref_name, 'dev') && format('ghcr.io/{0}:dev', github.repository) || format('ghcr.io/{0}:latest', github.repository)  }}
